// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymyxojxjetrcgzutscvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlteXhvanhqZXRyY2d6dXRzY3ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4ODgzMjksImV4cCI6MjA2MzQ2NDMyOX0.HYc36Rpb29Sb5XLHLlMCze9KfBRza4ndUWgGf9ieDP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);